# Herrm I have created a template to make an EC2 instance using 
# the default security group, which comes in built with a VPC.

AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance

Resources:
  DevEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
        ImageId: ami-016b213e65284e9c9
        InstanceType: t2.micro
        KeyName: cfn-key1
        SecurityGroups:
          - default # The dash indicates a list