AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating an EC2 Instance with new instance type and key"
Resources:
  MyEC2Instance:
    Properties:
      ImageId: "ami-016b213e65284e9c9"
      Type: t2.small  # Note, this is not within the free tier
      KeyName: cfn-key1

# Also remember, during a change set, the AWS console does not apply the 
# change directly, but instead, to make an impact, waits for the user to 
# proceed with the execution. 