# This paramater creates a parameter for an AZ

AWSTemplateFormatVersion: 2010-09-09
Description: AZ Param Demo

Parameters:
  
  MyKeyNameList:
    Description: Allows the initiating user to create stack by choosing keys during setup
    Type: "AWS::EC2::KeyPair::KeyName"
  
  MyAZ:
    Description: Selecting an AZ (Availability Zone)
    Type: String
    Default: us-east-2
    AllowedValues:
      - us-east-2
      - us-east-1
      - us-west-1
      - us-west-2


Resources:
  DevEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-016b213e65284e9c9
      KeyName: !Ref MyKeyNameList
      InstanceType: t2.micro
      SecurityGroups:
        - default
        - !Ref MyCustomSecurityGroup
      AvailabilityZone: !Ref MyAZ
  
  MyCustomSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allowing SSH and HTTP over TCP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: '0.0.0.0/0'
  