# Creating a paramter type of AWS for KeyName property of EC2 instance
# I will parameteize teh Key Name 


AWSTemplateFormatVersion: 2010-09-09
Description: Adding additionla rules to our security group

Parameters:
  MyKeyName:
    Description: Allows the initiating user to create stack by choosing keys during setup
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  DevEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-016b213e65284e9c9
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup

  SSHSecurityGroup: # This is the second resource group
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH connection towards the EC2
      SecurityGroupIngress: 
        - IpProtocol: tcp 
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'

        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
  